### ISSUE TITLE
Regenerate README after releases are done

### ISSUE THREAD

**Issue by ralphtheninja** [Level/awesome#15]
Preconditions:

- [x] `level-js@3`
- [x] `level-browserify@2`

Also, ~~`level-js`~~ `level-browserify` description should include `leveldown` as well, since it bundles both `leveldown` and `level-js`.

**Comment by vweevers** [comment]
Apparently already done in 8ba8bff668d79943c3e1a7b6721f6ee1d8336302.

> level-browserify description should include leveldown as well, since it bundles both leveldown and level-js.

Done in 78a87659c2bf481840f5454dabe59953cd3a09a4.
