### ISSUE TITLE
Turn into a node module

### ISSUE THREAD

**Issue by ralphtheninja** [Level/awesome#5]
This way we can have repos dev-depend on it which will help with quering from npm to find level related modules.

**Comment by ralphtheninja** [comment]
_Or_ use the `level/community` repo. Which might suit better because of the name.

**Comment by vweevers** [comment]
Not sure I understand the goal?

**Comment by ralphtheninja** [comment]
The goal would be to be able to query for level related modules. Today this is basically lore, since you need to do research yourself, ask someone or check the awesome page. Maybe just overkill :)

**Comment by vweevers** [comment]
Though I agree npm has a huge gap when it comes to this, I don't like adding a dependency *just* for discoverability.

How about gulp's approach? They actively recommend authors to use the `gulpplugin` keyword, and have a [website](https://gulpjs.com/plugins/) that queries for this. Or well, the [npm](https://www.npmjs.com/search?q=keywords:level&page=1&ranking=optimal) and [npms](https://npms.io/search?q=keywords%3Alevel) websites do that too, as well as the cli: `npm search keywords:level`. We'd need a standard keyword.

**Comment by juliangruber** [comment]
doesn't every module (dev)depend on level* already?
