### ISSUE TITLE
Shorter dependency badges

### ISSUE THREAD

**Issue by vweevers** [Level/awesome#6]
Stumbled upon this trick of url-encoding a unicode icon. Some things we can do:

[![david](https://img.shields.io/david/level/leveldown.svg?label=%E2%81%9D)][1]
[![david](https://img.shields.io/david/level/level.js.svg?label=%E2%81%9D)][2]

[![david](https://img.shields.io/david/level/leveldown.svg?label=%E2%8A%9E)][1]
[![david](https://img.shields.io/david/level/level.js.svg?label=%E2%8A%9E)][2]

[![david](https://img.shields.io/david/level/leveldown.svg?label=%E2%99%A5)][1]
[![david](https://img.shields.io/david/level/level.js.svg?label=%E2%99%A5)][2]

[1]: https://david-dm.org/level/leveldown
[2]: https://david-dm.org/level/level.js

**Comment by MeirionHughes** [comment]
you can have a blank space; but having an icon seems better. 

![david](https://img.shields.io/david/level/leveldown.svg?label=🡻)

**Comment by ralphtheninja** [comment]
@vweevers Possible to have a happy smiley for positive/green and sad smiley for negative/red?

**Comment by vweevers** [comment]
@ralphtheninja sadly, no 😢
